# Generated by Django 4.1.3 on 2022-11-08 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodEvening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evening_test', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='GoodMorning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('morning_text', models.CharField(max_length=200)),
            ],
        ),
    ]
